
package ernestovargasexamen2;

/**
 *
 * @author ervargas
 */
public class Formularios extends javax.swing.JFrame {
    
    private int contador = 0; // Declaración del contador

    /**
     * Creates new form Formulario
     */
    public Formularios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VehiculoPropio = new javax.swing.ButtonGroup();
        Lnumencuesta = new javax.swing.JLabel();
        Lnumencuesta2 = new javax.swing.JLabel();
        Lnombre = new javax.swing.JLabel();
        Ledad = new javax.swing.JLabel();
        Lemail = new javax.swing.JLabel();
        Lcar = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        TFnombre = new javax.swing.JTextField();
        TFedad = new javax.swing.JTextField();
        TFemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Bguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(350, 465));
        getContentPane().setLayout(null);

        Lnumencuesta.setText("Numero de encuesta:");
        getContentPane().add(Lnumencuesta);
        Lnumencuesta.setBounds(20, 110, 140, 20);

        Lnumencuesta2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Lnumencuesta2);
        Lnumencuesta2.setBounds(170, 100, 150, 30);

        Lnombre.setText("Nombre:");
        getContentPane().add(Lnombre);
        Lnombre.setBounds(20, 160, 140, 20);

        Ledad.setText("Edad:");
        getContentPane().add(Ledad);
        Ledad.setBounds(20, 210, 140, 20);

        Lemail.setText("Correo electronico:");
        getContentPane().add(Lemail);
        Lemail.setBounds(20, 260, 140, 16);

        Lcar.setText("Vehiculo propio:");
        getContentPane().add(Lcar);
        Lcar.setBounds(20, 310, 140, 16);

        VehiculoPropio.add(jRadioButton1);
        jRadioButton1.setText("SI");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(170, 300, 60, 28);

        VehiculoPropio.add(jRadioButton2);
        jRadioButton2.setText("NO");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(260, 300, 60, 28);
        getContentPane().add(TFnombre);
        TFnombre.setBounds(170, 150, 150, 24);

        TFedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFedadActionPerformed(evt);
            }
        });
        getContentPane().add(TFedad);
        TFedad.setBounds(170, 200, 150, 24);
        getContentPane().add(TFemail);
        TFemail.setBounds(170, 250, 150, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("FORMULARIOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 20, 190, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 78, 350, 10);

        Bguardar.setText("Guardar informacion");
        Bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BguardarActionPerformed(evt);
            }
        });
        getContentPane().add(Bguardar);
        Bguardar.setBounds(100, 360, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFedadActionPerformed

    private void BguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BguardarActionPerformed
        
        // contador para el numero de encuesta
        contador++;
        Lnumencuesta2.setText(String.valueOf(contador));

         
        
    }//GEN-LAST:event_BguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formularios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bguardar;
    private javax.swing.JLabel Lcar;
    private javax.swing.JLabel Ledad;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Lnumencuesta;
    private javax.swing.JLabel Lnumencuesta2;
    private javax.swing.JTextField TFedad;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFnombre;
    private javax.swing.ButtonGroup VehiculoPropio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
