/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ernestovargasexamen2;

/**
 *
 * @author ervargas
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VehiculoPropio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Lnumencuesta = new javax.swing.JLabel();
        Lnombre = new javax.swing.JLabel();
        Ledad = new javax.swing.JLabel();
        Lemail = new javax.swing.JLabel();
        Lcar = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        TFnombre = new javax.swing.JTextField();
        TFedad = new javax.swing.JTextField();
        TFemail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(350, 300));
        getContentPane().setLayout(null);

        jLabel1.setText("Numero de encuesta:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 140, 30);

        Lnumencuesta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Lnumencuesta);
        Lnumencuesta.setBounds(160, 10, 150, 30);

        Lnombre.setText("Nombre:");
        getContentPane().add(Lnombre);
        Lnombre.setBounds(10, 70, 60, 16);

        Ledad.setText("Edad:");
        getContentPane().add(Ledad);
        Ledad.setBounds(10, 120, 31, 16);

        Lemail.setText("Correo electronico:");
        getContentPane().add(Lemail);
        Lemail.setBounds(10, 166, 101, 16);

        Lcar.setText("Vehiculo propio:");
        getContentPane().add(Lcar);
        Lcar.setBounds(10, 220, 100, 16);

        VehiculoPropio.add(jRadioButton1);
        jRadioButton1.setText("SI");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(160, 210, 60, 28);

        VehiculoPropio.add(jRadioButton2);
        jRadioButton2.setText("NO");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(250, 210, 60, 28);
        getContentPane().add(TFnombre);
        TFnombre.setBounds(160, 60, 150, 24);

        TFedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFedadActionPerformed(evt);
            }
        });
        getContentPane().add(TFedad);
        TFedad.setBounds(160, 110, 150, 24);
        getContentPane().add(TFemail);
        TFemail.setBounds(160, 160, 150, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcar;
    private javax.swing.JLabel Ledad;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Lnumencuesta;
    private javax.swing.JTextField TFedad;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFnombre;
    private javax.swing.ButtonGroup VehiculoPropio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
