
package ernestovargasexamen2;

/**
 *
 * @author ervargas
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Lcantidadencuestas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lcantidadvehiculos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lcabtidadsinvechiculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(470, 295));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Cantidad de encuestas:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 220, 20);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("PAGINA DE REPORTES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 280, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 80, 460, 2);

        Lcantidadencuestas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Lcantidadencuestas);
        Lcantidadencuestas.setBounds(260, 90, 160, 30);

        jLabel4.setText("Cantidad de personas con vehiculo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 220, 20);

        Lcantidadvehiculos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Lcantidadvehiculos);
        Lcantidadvehiculos.setBounds(260, 140, 160, 30);

        jLabel6.setText("Cantidad de personas sin vehiculo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 220, 20);

        Lcabtidadsinvechiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Lcabtidadsinvechiculo);
        Lcabtidadsinvechiculo.setBounds(260, 200, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // mostrar cantidad de encuestas
        Lcantidadencuestas.setText(String.valueOf(ErnestoVargasExamen2.cantidadencuestas));

        // mostrar cantidad de personas con vehiculo
        Lcantidadvehiculos.setText(String.valueOf(ErnestoVargasExamen2.cantidadvehiculos));

        // mostrar cantidad de personas sin vehiculo
        Lcabtidadsinvechiculo.setText(String.valueOf(ErnestoVargasExamen2.cantidadsinvehiculo));


    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcabtidadsinvechiculo;
    private javax.swing.JLabel Lcantidadencuestas;
    private javax.swing.JLabel Lcantidadvehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
